### ISSUE TITLE
Merge "Duplicate" Endpoints

### ISSUE THREAD

**Issue by DJSethDuncan** [lake-afton-public-observatory/lapo-api#1]
I'd like to get these following endpoints merged:

- `/sun` and `/sun2`
- `/moon` and `/moon2`

**Comment by nessalc** [comment]
I'm working on calculating the data for these myself. Once this is done, these endpoints can be more easily merged, because Python right now is the bottleneck on all the `<object>2` endpoints.

I'm pretty close on duplicating info from `/sun`, but some things from `/sun2` are giving me fits. We can probably, at least temporarily, ditch `mag` and `earth_dist`&mdash;the magnitude doesn't change all that much for the sun, and the earth distance, while nice, isn't entirely necessary.

I'm nowhere on the moon calculations right now...

**Comment by DJSethDuncan** [comment]
Sweet, thanks for the update.

Just have `mag` always return `hella bright`
